# Generated by Django 4.1.7 on 2023-07-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_contactmessage_alter_generator_power_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(default='2023-01-01 00:00:00'),
        ),
    ]
