# Generated by Django 4.2.3 on 2023-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_contactmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generator_images/'),
        ),
    ]
