# Generated by Django 4.2.4 on 2023-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_generator_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
